import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

String _appTheme = "primary";

/// Helper class for managing themes and colors.
class ThemeHelper {
  // A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    _appTheme = _newTheme;
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: colorScheme.primary,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(
              35,
            ),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      dividerTheme: DividerThemeData(
        thickness: 1,
        space: 1,
        color: appTheme.gray700,
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyMedium: TextStyle(
          color: appTheme.black900,
          fontSize: getFontSize(
            14,
          ),
          fontFamily: 'Inter',
          fontWeight: FontWeight.w400,
        ),
        displayMedium: TextStyle(
          color: appTheme.black900,
          fontSize: getFontSize(
            40,
          ),
          fontFamily: 'Inter',
          fontWeight: FontWeight.w700,
        ),
        headlineLarge: TextStyle(
          color: appTheme.red300.withOpacity(0.7),
          fontSize: getFontSize(
            32,
          ),
          fontFamily: 'Inter',
          fontWeight: FontWeight.w700,
        ),
        headlineSmall: TextStyle(
          color: appTheme.black900,
          fontSize: getFontSize(
            24,
          ),
          fontFamily: 'Jost',
          fontWeight: FontWeight.w500,
        ),
        titleLarge: TextStyle(
          color: appTheme.black900,
          fontSize: getFontSize(
            20,
          ),
          fontFamily: 'Inter',
          fontWeight: FontWeight.w600,
        ),
        titleMedium: TextStyle(
          color: appTheme.black900,
          fontSize: getFontSize(
            16,
          ),
          fontFamily: 'Inter',
          fontWeight: FontWeight.w600,
        ),
        titleSmall: TextStyle(
          color: appTheme.black900,
          fontSize: getFontSize(
            14,
          ),
          fontFamily: 'Inter',
          fontWeight: FontWeight.w700,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFFADD8CE),
    
    primaryContainer: Color(0XB20B4464),
    secondary: Color(0XB20B4464),
    secondaryContainer: Color(0XFFADD8CE),
    tertiary: Color(0XB20B4464),
    tertiaryContainer: Color(0XFFADD8CE),

    // Background colors
    background: Color(0XB20B4464),

    // Surface colors
    surface: Color(0XB20B4464),
    surfaceTint: Color(0XFF231F20),
    surfaceVariant: Color(0XFFADD8CE),

    // Error colors
    error: Color(0XFF231F20),
    errorContainer: Color(0XFF0B91DD),
    onError: Color(0XFF06F8A1),
    onErrorContainer: Color(0XFF1E1E1E),

    // On colors(text colors)
    onBackground: Color(0XE5FFFFFF),
    onInverseSurface: Color(0XFF06F8A1),
    onPrimary: Color(0XFF231F20),
    onPrimaryContainer: Color(0XE5FFFFFF),
    onSecondary: Color(0XE5FFFFFF),
    onSecondaryContainer: Color(0XFF231F20),
    onTertiary: Color(0XE5FFFFFF),
    onTertiaryContainer: Color(0XFF231F20),

    // Other colors
    outline: Color(0XFF231F20),
    outlineVariant: Color(0XB20B4464),
    scrim: Color(0XB20B4464),
    shadow: Color(0XFF231F20),

    // Inverse colors
    inversePrimary: Color(0XB20B4464),
    inverseSurface: Color(0XFF231F20),

    // Pending colors
    onSurface: Color(0XE5FFFFFF),
    onSurfaceVariant: Color(0XFF231F20),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Amber
  Color get amber500 => Color(0XFFFFC107);

  // Black
  Color get black900 => Color(0XFF000000);

  // BlueGray
  Color get blueGray100 => Color(0XFFD9D9D9);
  Color get blueGray300 => Color(0XFF75B7A6);
  Color get blueGray400 => Color(0XFF888888);
  Color get blueGray600 => Color(0XFF4F6577);
  Color get blueGray900 => Color(0XFF292D32);

  // Gray
  Color get gray400 => Color(0XFFD8BAB9);
  Color get gray700 => Color(0XFF605151);
  Color get gray70001 => Color(0XFF545A56);
  Color get gray70002 => Color(0XFF5A5252);
  Color get gray70003 => Color(0XFF576065);
  Color get gray7001 => Color.fromARGB(255, 175, 194, 204);

  // GreenAFc
  Color get greenA400Fc => Color(0XFC01BF7A);

  // Red
  Color get red200 => Color(0XFFC89B8B);
  Color get red300 => Color(0XFFB18071);
  Color get whiteA700 => Color(0XFFFFFFFF);
  Color get teal100 => Color(0XFFADD8CE);
  Color get gray800 => Color(0XFF504848);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
